---
title: "R Notebook"
output: html_notebook
---

## imports

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
```

## nested model comparison

```{r}
d <- read_csv('./photodraw_tracing.csv') %>%
  mutate(tracing_item = factor(tracing_item, levels = c('this square', 'this shape', 'this circle')), 
         condition = factor(condition, levels = c('S', 'W', 'P'))) 
  # mutate(age = scale(age, center = TRUE, scale = FALSE),
  #        post_mse = scale(post_mse, center = TRUE, scale = FALSE))
m1 = lmer(post_mse ~ age + (1 | session_id), data=d)
m2 = lmer(post_mse ~ age + (1 | session_id) + (1 | tracing_item), data=d)
m3 = lmer(post_mse ~ age + tracing_item + (1 | session_id), data=d)
m4 = lmer(post_mse ~ age + (1 | session_id) + (1 + age | tracing_item), data=d)
anova(m1, m2, m3, m4)
```

## Look at interactiosn between age and tracing item

```{r}
# contrasts(d$tracing_item) <- contr.treatment(3, base = 1)
# summary(lmer(post_mse ~ age * tracing_item + (1 | session_id), data=d))
```

## Look at best model 

```{r}
summary(m3)
```

## Visualize data

```{r}
d %>%
  gather(registration, val, pre_mse, post_mse) %>%
  ggplot(aes(x = age, y = val, color = tracing_item)) +
    geom_point() +
    geom_smooth(method = 'lm') +
    facet_wrap(~ registration) +
    theme_bw() +
    theme(aspect.ratio = 1) 
```

```{r}
d %>%
  gather(transformation, val, rotate, translate, scale) %>%
  ggplot(aes(x = age, y = val, color = tracing_item)) +
    geom_point() +
    geom_smooth(method = 'lm') +
    facet_wrap(~ transformation) +
    theme_bw() +
    theme(aspect.ratio = 1) +
    ylim(-0.05, 0.4)

```

```{r}
m1 = lmer(correct ~ age + condition + (1 | session_id), data=d)
m2 = lmer(correct ~ age + condition + (1 | tracing_item) + (1 | session_id), data=d)
#m3 = lmer(correct ~ age + tracing_item + post_mse + pre_mse + (1 | session_id), data=d)
#m4 = lmer(correct ~ post_mse + (1 | session_id), data=d)
anova(m1, m2)
```
```{r}
summary(m4)
summary(d$correct)
```

Examine how the shape error and spatial error would predict human judgments
```{r}
library(lme4)
rater_data <- read.csv('./photodraw_summary.csv')
lm_rate = lm(formula=rater1 ~ spatial + post_mse, data=rater_data)
summary(lm_rate)
```

```{r}
ggplot(rater_data, aes(spatial, rater1, color=tracing_item)) +
  geom_smooth(method="lm") +
  geom_point(size=3) +
  theme_bw() + 
  xlab("spatial error") +
  ylab("human judgment") +
  ggtitle('Spatial Error vs. Human judgment')
```

```{r}
ggplot(rater_data, aes(post_mse, rater1, color=tracing_item)) +
  geom_smooth(method="lm") +
  geom_point(size=3) +
  theme_bw() + 
  xlab("spatial error") +
  ylab("human judgment") +
  ggtitle('Spatial Error vs. Human judgment')
```

```{r}
library(MASS)
rater_data <- read.csv('./photodraw_summary_mse.csv')
rater_data$rater1 <- factor(rater_data$rater1, levels = c("0", "1", "2", "3", "4"), ordered=TRUE)
rater_data$post_tran = scale(rater_data$post_tran)
rater_data$spatial = scale(rater_data$spatial)
ord_m <- polr(rater1 ~ spatial + post_tran, rater_data, Hess=TRUE)

summary(ord_m)
ctable <- coef(summary(ord_m))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
(ctable <- cbind(ctable, "p value" = p))

print('exp(coefficient of spatial and post_tran)')
exp(coef(ord_m))

```
split the data by tracing items

```{r}
square = subset(rater_data, tracing_item=='this square')
ord_m <- polr(rater1 ~ spatial + post_tran, rater_data, Hess=TRUE)

summary(ord_m)
ctable <- coef(summary(ord_m))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
(ctable <- cbind(ctable, "p value" = p))

print('exp(coefficient of spatial and post_tran)')
exp(coef(ord_m))
```

```{r}
ord2 <- polr(rater1 ~ spatial, rater_data, Hess=TRUE)

summary(ord2)
ctable <- coef(summary(ord2))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
(ctable <- cbind(ctable, "p value" = p))

print('exp(coefficient of spatial)')
exp(coef(ord2))

```

```{r}
ord2 <- polr(rater1 ~ post_mse, rater_data, Hess=TRUE)

summary(ord2)
ctable <- coef(summary(ord2))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
(ctable <- cbind(ctable, "p value" = p))

print('exp(coefficient of post_mse)')
exp(coef(ord2))
```

